WIP: Add missing tests to `styles.py`
cordada/drf-pagination-utils pull request #154
Opened 2023-08-31 15:01 UTC by svillegas-cdd

* Added tests to `styles.ObjectCountHeaderPageNumberPagination`

Ref: https://cordada.aha.io/features/COMPCLDATA-253

2023-09-01 15:18 UTC, fpinto-cdd approved these changes

2023-09-04 23:38 UTC, jtrobles-cdd requested changes

2023-09-04 23:38 UTC, jtrobles-cdd commented on fyntex/drf_pagination_utils/tests/test_styles.py
> +        self.assertEqual(response.status_code, status.HTTP_200_OK)
```suggestion
        self.assertEqual(response.status_code, http.HTTPStatus.OK)
```

2023-09-04 23:38 UTC, jtrobles-cdd commented on fyntex/drf_pagination_utils/tests/test_styles.py
> +        self.assertEqual(response.status_code, status.HTTP_200_OK)
```suggestion
        self.assertEqual(response.status_code, http.HTTPStatus.OK)
```

2023-09-04 23:38 UTC, jtrobles-cdd commented on fyntex/drf_pagination_utils/tests/test_styles.py
> +        self.assertEqual(response.status_code, status.HTTP_200_OK)
```suggestion
        self.assertEqual(response.status_code, http.HTTPStatus.OK)
```

2023-09-04 23:38 UTC, jtrobles-cdd commented on fyntex/drf_pagination_utils/tests/test_styles.py
> +from rest_framework import status
```suggestion
```

2023-09-04 23:38 UTC, jtrobles-cdd commented on fyntex/drf_pagination_utils/tests/test_styles.py
> +        }
Reformat

```suggestion
        expected_headers = {
            'Content-Type': 'text/html; charset=utf-8',
            'Link': (
                '<https://example.com/api/v1/endpoint/?page=2>; rel="next", '
                '<https://example.com/api/v1/endpoint/?page=4>; rel="last"'
            ),
        }
```

2023-09-04 23:38 UTC, jtrobles-cdd commented on fyntex/drf_pagination_utils/tests/test_styles.py
> +            '<https://example.com/api/v1/endpoint/?page=4>; rel="last"',
Reformat

```suggestion
            'Link': (
                '<https://example.com/api/v1/endpoint/>; rel="first", '
                '<https://example.com/api/v1/endpoint/>; rel="previous", '
                '<https://example.com/api/v1/endpoint/?page=3>; rel="next", '
                '<https://example.com/api/v1/endpoint/?page=4>; rel="last"'
            ),
```

2023-09-04 23:38 UTC, jtrobles-cdd commented on fyntex/drf_pagination_utils/tests/test_styles.py
> +                },
Reformat

```suggestion
                'collection_first_page': {
                    'description': (
                    'First page of the collection of items.\n\n'
                    'Use the URL returned in the relation type `first` of the response `Link` '
                    'header.'
                    )
                },
                'collection_previous_page': {
                    'description': (
                    'Previous page of the collection of items.\n\n'
                    'Use the URL returned in the relation type `previous` of the response `Link` '
                    'header.'
                    )
                },
                'collection_next_page': {
                    'description': (
                    'Next page of the collection of items.\n\n'
                    'Use the URL returned in the relation type `next` of the response `Link` '
                    'header.'
                    )
                },
                'collection_last_page': {
                    'description': (
                    'Last page of the collection of items.\n\n'
                    'Use the URL returned in the relation type `last` of the response `Link` '
                    'header.'
                    )
                },
```

2023-09-04 23:38 UTC, jtrobles-cdd commented on fyntex/drf_pagination_utils/tests/test_styles.py
> +                            '<http://www.example.com/example-items/?page=42>; rel="last"',
Reformat

```suggestion
                            'summary': (
                            'Link Header Page Number Pagination.\n\n'
                            'A simple page number–based style that supports page numbers as query '
                            'parameters\nand includes pagination links in an RFC 8288–compliant '
                            '`Link` header.',
                            'value': '<http://www.example.com/example-items/>; rel="first", '
                            '<http://www.example.com/example-items/?page=3>; rel="previous", '
                            '<http://www.example.com/example-items/?page=5>; rel="next", '
                            '<http://www.example.com/example-items/?page=42>; rel="last"'
                            ),
```

2023-09-04 23:38 UTC, jtrobles-cdd commented on fyntex/drf_pagination_utils/tests/test_styles.py
> +        )
```suggestion
        self.pagination_obj_1.request = mock.create_autospec(
            rest_framework.request.Request,
            instance=True,
            build_absolute_uri=mock.Mock(
                return_value='https://example.com/api/v1/endpoint/',
            ),
        )
```

2023-09-04 23:38 UTC, jtrobles-cdd commented on fyntex/drf_pagination_utils/tests/test_styles.py
> +        )
```suggestion
        self.pagination_obj_2.request = mock.create_autospec(
            rest_framework.request.Request,
            instance=True,
            build_absolute_uri=mock.Mock(
                return_value='https://example.com/api/v1/endpoint/',
            ),
        )
```

2023-09-04 23:38 UTC, jtrobles-cdd commented on fyntex/drf_pagination_utils/tests/test_styles.py
> +        )
```suggestion
        self.pagination_obj_1.request = mock.create_autospec(
            rest_framework.request.Request,
            instance=True,
            build_absolute_uri=mock.Mock(
                return_value='https://example.com/api/v1/endpoint/',
            )
        )
```

2023-09-04 23:38 UTC, jtrobles-cdd commented on fyntex/drf_pagination_utils/tests/test_styles.py
> +        )
```suggestion
        self.pagination_obj_2.request = mock.create_autospec(
            rest_framework.request.Request,
            instance=True,
            build_absolute_uri=mock.Mock(
                return_value='https://example.com/api/v1/endpoint/',
            )
        )
```

2023-09-04 23:38 UTC, jtrobles-cdd commented on fyntex/drf_pagination_utils/tests/test_styles.py
> +        )
```suggestion
        self.pagination_obj_3.request = mock.create_autospec(
            rest_framework.request.Request,
            instance=True,
            build_absolute_uri=mock.Mock(
                return_value='https://example.com/api/v1/endpoint/',
            )
        )
```

2023-09-05 15:08 UTC, jtrobles-cdd approved these changes

2023-09-05 15:52 UTC, merged